<?php
class vo_viFacturaDetalle1{
	 public $idfactura;
	 public $idcontrato;
	 public $idclireg;
	 public $serie;
	 public $folio;
	 public $forma_pago;
	 public $metodo_pago;
	 public $referencia;
	 public $calcular_iva;
	 public $retener_isr;
	 public $retener_iva;
	 public $importe;
	 public $descuento;
	 public $iva;
	 public $total;
	 public $email;
	 public $idcontpaq;
	 public $idrecibo;
	 public $total_abono;
	 public $status;
	 public $fecha_total_pagado;
	 public $isfe;
	 public $UUID;
	 public $pdf;
	 public $xml;
	 public $guia;
	 public $razon_social;
	 public $rfc;
	 public $curp;
	 public $calle;
	 public $colonia;
	 public $ciudad;
	 public $localidad;
	 public $municipio;
	 public $estado;
	 public $pais;
	 public $email_cli;
	 public $idcodpos;
	 public $cuenta;
	 public $desc_cuenta;
}
?>